### ISSUE TITLE
link to repos doesn't work

### ISSUE THREAD

**Issue by stonematt** [w3c/verifiable-claims#16]
this link doesn't work: 

https://github.com/search?q=topic%3Averifiable+claims+org%3Aw3c&type=Repositories

how to we make a "topic"?

**Comment by stonematt** [comment]
Actually, there are 2 links to repos.  the second one works: 

https://github.com/search?q=verifiable-claims+org%3Aw3c&type=Repositories 

let's update the first link w/ this url - I may try to do that....

**Comment by liamquin** [comment]
fixed, thanks for the report.
